---
- name: activity 3 install apache and php
  become: yes
  hosts: all
  tasks:
    - name: install apache
      ansible.builtin.dnf:
        name:
          - httpd
          - php
          - php-cli
          - php-common
        state: present
    - name: create info.php
      ansible.builtin.copy:
        content: '<?php phpinfo(); ?>'
        dest: /var/www/html/info.php/var/www/html/info.ph
    - name: ensure httpd is running
      ansible.builtin.service:
        name: httpd
        enabled: yes
        state: starte
